### PR TITLE
Refactoring Argument parsing functions

### PR DESCRIPTION
**Pull request by kiavash-at-work**
This is a fast and dirty attempt to refactor as much code as possible to make CLI binary and PAM module arguments use the common functions minimizing the duplicate codes.

I have only sanity checked it and didn't test against all possible combinations.

### CODE REVIEW

**Review by ashuio — COMMENTED** [review]
Should we really do that?
It might cause confusion in future when we have to change or add args
like for eg. pam can have auth args as well as session args which both will be diffrent.

Further i have also plans to remove args from pam entirely and move towards config file for multi user setups.

**Comment by kiavash-at-work** [comment]
Now that I know the future plan of having different the arguments for PAM and BIN, I will update the PR to keep them separate and not reuse the common args.

**Comment by ashuio** [comment]
Thanks, Let me know and i'll Merge it right ahead.

Thanks for the code.

**Comment by kiavash-at-work** [comment]
No problem.

I reverted the common arguments back to keep PAM and BIN separate.

**Comment by ashuio** [comment]
Perfect, Good to merge from your side?

**Comment by kiavash-at-work** [comment]
The written unit tests all passed, and I did some sanity checks for the rest of the code, however with no 100% unit test and integration coverage, I hope I didn't introduce a regression. If your tests are also ok, then please merge.

**Comment by ashuio** [comment]
LGTM, I'll also rewrite the README and merge this branch to main today.

Now i only need to implement a config file for the pam_module and it should be pretty well rounded solution.

**Pull request merged**
