### PR TITLE
Unit tests for filehash.rs

### PR DESCRIPTION
**Pull request by kiavash-at-work**
This PR contains:
1. Implementation of unit tests for `filehash.rs`
   - Some of the tests depends on known locally generated files, they will run sequentially.
      - The test files will be generated by the unit test code,
      - The test files/folder will be deleted at the end of the unit test code.
2. `filehash.rs` is refactored to streamline the unit tests and error handling.

### CODE REVIEW

**Comment by ashuio** [comment]
Thanks for another PR, A couple of things,

Can you have a look at the new branch i made for 0.1.4 

Also i feel a lil uneasy about the huge Google copyright notices in the files since Users might get the wrong idea that this is a Google backed project or something.

**Comment by kiavash-at-work** [comment]
I will certainly take a close look at 0.1.4. Just noticed it now that you mentioned. If I understand correctly, the goal of that branch is to separate the codes to a main executable and multiple binary modules, instead of all in a single executable. That sounds good!

Regarding your question, [This page](https://opensource.google/docs/patching/) may help describing and answering the questions regarding patching open source projects by Google employees. I think the norm is that all files should have complete license headers.

**Comment by ashuio** [comment]
Yeah, basically my goal was to replace pam_exec.so module with our own so we can do stuff like unmount datasets on logout and also have more granular control over the process.

I have loads of changes i haven't commited yet, Just trying to finalise the project structure.

Thanks for the google contribution page link on that age i see this 

> When contributing to third-party projects, Googlers do not need to add Google’s copyright notice when authoring patches to existing files. Googlers should add Google’s copyright notice (or a “The Project Authors” style copyright notice) to new files being added to the library if permitted by the project maintainers.

So i think we should be Good since the copyright is implied.

**Comment by kiavash-at-work** [comment]
Thank you. I will make sure to follow as recommended and inline with your code and our policy for the existing files.

Regarding `0.1.4` that sounds like a really good plan. I have been start studying that branch and once your updates are committed, I try to submit my unit tests to that branch. I think we can close this PR without committing it to `main`.

**Pull request closed without merging**
